In [2]:
import pandas as pd

# check all csv files in the directory

import os
report = []
for file in os.listdir():

    if file.endswith(".csv"):
        print(file)

        # read the csv file
        df = pd.read_csv(file)

        # check the first 5 rows of the data
        print(df.head())

        # check the last 5 rows of the data
        print(df.tail())

        # check the shape of the data
        print(df.shape)

        # check the data types of the columns
        print(df.dtypes)

        # check the column names
        print(df.columns)

        # check the summary statistics of the data
        print(df.describe())

        # check for missing values
        print(df.isnull().sum())

        # check for duplicated rows
        print(df.duplicated().sum())

        report.append({
            "summary": df.describe(),
            "missing": df.isnull().sum(),
            "duplicated": df.duplicated().sum()
        })

# save the report to a csv file
pd.DataFrame(report).to_csv("report.csv", index=False)

Ganison_dataset_1.csv
                              school_name  year  StudentID    First Name  \
0  Christ King Catholic School, Bass Hill  2022          1  First Name 1
1  Christ King Catholic School, Bass Hill  2022          1  First Name 1
2  Christ King Catholic School, Bass Hill  2022          1  First Name 1
3  Christ King Catholic School, Bass Hill  2022          1  First Name 1
4  Christ King Catholic School, Bass Hill  2022          1  First Name 1

     Last Name  Year Level    Class  Subject Answers Correct Answers  ...  \
0  Last Name 1           1  Class 1  Science       C               B  ...
1  Last Name 1           1  Class 1  Science       C               B  ...
2  Last Name 1           1  Class 1  Science       C               C  ...
3  Last Name 1           1  Class 1  Science       B               D  ...
4  Last Name 1           1  Class 1  Science       A               B  ...

   correct_answer_percentage_per_class average_score school_percentile  \
0                                 3.04         60.39                81
1                                45.56         12.81                22
2                                48.49         20.34                53
3                                21.97          9.93                93
4                                70.32         39.01                68

   sydney_percentile  strength_status  high_distinct_count  distinct_count  \
0                 77                E                   62              28
1                  4                E                   77               4
2                 25                E                   62              25
3                 72                E                   76              64
4                 92                E                   20              15

   credit_count  participant_count          award
0            41                 34  Participation
1            88                 24  Participation
2            97                 44  Participation
3            77                 91  Participation
4            90                 59  Participation

[5 rows x 31 columns]
                                   school_name  year  StudentID  \
799995  Christ King Catholic School, Bass Hill  2022      16000
799996  Christ King Catholic School, Bass Hill  2022      16000
799997  Christ King Catholic School, Bass Hill  2022      16000
799998  Christ King Catholic School, Bass Hill  2022      16000
799999  Christ King Catholic School, Bass Hill  2022      16000

              First Name        Last Name  Year Level    Class Subject  \
799995  First Name 16000  Last Name 16000           4  Class 4    Math
799996  First Name 16000  Last Name 16000           4  Class 4    Math
799997  First Name 16000  Last Name 16000           4  Class 4    Math
799998  First Name 16000  Last Name 16000           4  Class 4    Math
799999  First Name 16000  Last Name 16000           4  Class 4    Math

       Answers Correct Answers  ...  correct_answer_percentage_per_class  \
799995       C               A  ...                                22.13
799996       C               D  ...                                35.07
799997       C               B  ...                                34.20
799998       A               Z  ...                                 7.67
799999       A               C  ...                                88.94

       average_score school_percentile  sydney_percentile  strength_status  \
799995         78.60                72                 49                E
799996         28.82                22                 35                E
799997          1.18                42                 65                E
799998         78.06                10                 21                E
799999         93.57               100                 83                E

        high_distinct_count  distinct_count  credit_count  participant_count  \
799995                   17              62            62                 39
799996                   68              64            61                 43
799997                   39              19            93                 85
799998                   85              96            95                 77
799999                   41              44            49                 49

                award
799995  Participation
799996  Participation
799997  Participation
799998  Participation
799999  Participation

[5 rows x 31 columns]
(800000, 31)
school_name                             object
year                                     int64
StudentID                                int64
First Name                              object
Last Name                               object
Year Level                               int64
Class                                   object
Subject                                 object
Answers                                 object
Correct Answers                         object
Question Number                          int64
Subject Contents                        object
Assessment Areas                        object
sydney_correct_count_percentage        float64
sydney_average_score                   float64
sydney_participants                      int64
student_score                          float64
student_total_assessed                   int64
student_area_assessed_score            float64
total_area_assessed_score              float64
participant                              int64
correct_answer_percentage_per_class    float64
average_score                          float64
school_percentile                        int64
sydney_percentile                        int64
strength_status                         object
high_distinct_count                      int64
distinct_count                           int64
credit_count                             int64
participant_count                        int64
award                                   object
dtype: object
Index(['school_name', 'year', 'StudentID', 'First Name', 'Last Name',
       'Year Level', 'Class', 'Subject', 'Answers', 'Correct Answers',
       'Question Number', 'Subject Contents', 'Assessment Areas',
       'sydney_correct_count_percentage', 'sydney_average_score',
       'sydney_participants', 'student_score', 'student_total_assessed',
       'student_area_assessed_score', 'total_area_assessed_score',
       'participant', 'correct_answer_percentage_per_class', 'average_score',
       'school_percentile', 'sydney_percentile', 'strength_status',
       'high_distinct_count', 'distinct_count', 'credit_count',
       'participant_count', 'award'],
      dtype='object')
           year      StudentID     Year Level  Question Number  \
count  800000.0  800000.000000  800000.000000    800000.000000
mean     2022.0    8000.500000       6.491562        13.000000
std         0.0    4618.805031       3.442121         7.211107
min      2022.0       1.000000       1.000000         1.000000
25%      2022.0    4000.750000       4.000000         7.000000
50%      2022.0    8000.500000       6.500000        13.000000
75%      2022.0   12000.250000       9.000000        19.000000
max      2022.0   16000.000000      12.000000        25.000000

       sydney_correct_count_percentage  sydney_average_score  \
count                    800000.000000         800000.000000
mean                         50.002762             49.996921
std                          28.871401             28.867806
min                           0.000000              0.000000
25%                          25.000000             24.960000
50%                          50.000000             50.020000
75%                          75.000000             74.970000
max                         100.000000            100.000000

       sydney_participants  student_score  student_total_assessed  \
count        800000.000000  800000.000000           800000.000000
mean             54.974225      50.015637               55.012504
std              26.278214      28.857599               26.253684
min              10.000000       0.000000               10.000000
25%              32.000000      25.030000               32.000000
50%              55.000000      50.030000               55.000000
75%              78.000000      75.010000               78.000000
max             100.000000     100.000000              100.000000

       student_area_assessed_score  total_area_assessed_score    participant  \
count                800000.000000              800000.000000  800000.000000
mean                     49.987962                  49.967346      55.005586
std                      28.883495                  28.837838      26.239458
min                       0.000000                   0.000000      10.000000
25%                      24.950000                  24.980000      32.000000
50%                      49.980000                  49.920000      55.000000
75%                      75.010000                  74.930000      78.000000
max                     100.000000                 100.000000     100.000000

       correct_answer_percentage_per_class  average_score  school_percentile  \
count                        800000.000000  800000.000000      800000.000000
mean                             50.014546      49.996848          50.506750
std                              28.850701      28.878929          28.852988
min                               0.000000       0.000000           1.000000
25%                              25.050000      24.990000          26.000000
50%                              50.010000      49.970000          50.000000
75%                              75.000000      75.010000          75.000000
max                             100.000000     100.000000         100.000000

       sydney_percentile  high_distinct_count  distinct_count   credit_count  \
count      800000.000000        800000.000000   800000.000000  800000.000000
mean           50.498029            50.552483       50.444415      50.487684
std            28.866903            28.843751       28.867169      28.859805
min             1.000000             1.000000        1.000000       1.000000
25%            25.000000            26.000000       25.000000      25.000000
50%            50.000000            51.000000       50.000000      51.000000
75%            76.000000            76.000000       75.000000      75.000000
max           100.000000           100.000000      100.000000     100.000000

       participant_count
count      800000.000000
mean           50.497451
std            28.846328
min             1.000000
25%            25.000000
50%            51.000000
75%            75.000000
max           100.000000
school_name                            0
year                                   0
StudentID                              0
First Name                             0
Last Name                              0
Year Level                             0
Class                                  0
Subject                                0
Answers                                0
Correct Answers                        0
Question Number                        0
Subject Contents                       0
Assessment Areas                       0
sydney_correct_count_percentage        0
sydney_average_score                   0
sydney_participants                    0
student_score                          0
student_total_assessed                 0
student_area_assessed_score            0
total_area_assessed_score              0
participant                            0
correct_answer_percentage_per_class    0
average_score                          0
school_percentile                      0
sydney_percentile                      0
strength_status                        0
high_distinct_count                    0
distinct_count                         0
credit_count                           0
participant_count                      0
award                                  0
dtype: int64
0
Ganison_dataset_2.csv
                              school_name  year  StudentID    First Name  \
0  Christ King Catholic School, Bass Hill  2022          1  First Name 1
1  Christ King Catholic School, Bass Hill  2022          1  First Name 1
2  Christ King Catholic School, Bass Hill  2022          1  First Name 1
3  Christ King Catholic School, Bass Hill  2022          1  First Name 1
4  Christ King Catholic School, Bass Hill  2022          1  First Name 1

     Last Name  Year Level    Class  Subject Answers Correct Answers  ...  \
0  Last Name 1           2  Class 2  History       D               C  ...
1  Last Name 1           2  Class 2  History       C               C  ...
2  Last Name 1           2  Class 2  History       D               B  ...
3  Last Name 1           2  Class 2  History       A               A  ...
4  Last Name 1           2  Class 2  History       A               A  ...

   correct_answer_percentage_per_class average_score school_percentile  \
0                                29.04         32.86                 6
1                                37.81         15.23                96
2                                69.54         11.70                77
3                                86.83         95.92                17
4                                39.44          9.67                95

   sydney_percentile  strength_status  high_distinct_count  distinct_count  \
0                 40                W                   51              90
1                 44                W                   64              86
2                  1                W                   21              23
3                 23                W                   58              12
4                 14                W                   41              19

   credit_count  participant_count   award
0            33                 84  Credit
1            70                 88  Credit
2            47                 78  Credit
3            86                 91  Credit
4            11                 97  Credit

[5 rows x 31 columns]
                                   school_name  year  StudentID  \
799995  Christ King Catholic School, Bass Hill  2022      16000
799996  Christ King Catholic School, Bass Hill  2022      16000
799997  Christ King Catholic School, Bass Hill  2022      16000
799998  Christ King Catholic School, Bass Hill  2022      16000
799999  Christ King Catholic School, Bass Hill  2022      16000

              First Name        Last Name  Year Level    Class  Subject  \
799995  First Name 16000  Last Name 16000           6  Class 6  English
799996  First Name 16000  Last Name 16000           6  Class 6  English
799997  First Name 16000  Last Name 16000           6  Class 6  English
799998  First Name 16000  Last Name 16000           6  Class 6  English
799999  First Name 16000  Last Name 16000           6  Class 6  English

       Answers Correct Answers  ...  correct_answer_percentage_per_class  \
799995       A               C  ...                                25.51
799996       A               Z  ...                                10.18
799997       B               B  ...                                83.56
799998       A               B  ...                                32.52
799999       D               D  ...                                66.00

       average_score school_percentile  sydney_percentile  strength_status  \
799995         40.48                20                 18                W
799996         53.73                97                 75                W
799997         32.65                24                  9                W
799998          4.51                59                 69                W
799999         42.68                 9                 95                W

        high_distinct_count  distinct_count  credit_count  participant_count  \
799995                   35              19            75                 72
799996                   30              34            19                 11
799997                   73              40            74                 51
799998                   13              64            31                  5
799999                   59              20            29                 35

         award
799995  Credit
799996  Credit
799997  Credit
799998  Credit
799999  Credit

[5 rows x 31 columns]
(800000, 31)
school_name                             object
year                                     int64
StudentID                                int64
First Name                              object
Last Name                               object
Year Level                               int64
Class                                   object
Subject                                 object
Answers                                 object
Correct Answers                         object
Question Number                          int64
Subject Contents                        object
Assessment Areas                        object
sydney_correct_count_percentage        float64
sydney_average_score                   float64
sydney_participants                      int64
student_score                          float64
student_total_assessed                   int64
student_area_assessed_score            float64
total_area_assessed_score              float64
participant                              int64
correct_answer_percentage_per_class    float64
average_score                          float64
school_percentile                        int64
sydney_percentile                        int64
strength_status                         object
high_distinct_count                      int64
distinct_count                           int64
credit_count                             int64
participant_count                        int64
award                                   object
dtype: object
Index(['school_name', 'year', 'StudentID', 'First Name', 'Last Name',
       'Year Level', 'Class', 'Subject', 'Answers', 'Correct Answers',
       'Question Number', 'Subject Contents', 'Assessment Areas',
       'sydney_correct_count_percentage', 'sydney_average_score',
       'sydney_participants', 'student_score', 'student_total_assessed',
       'student_area_assessed_score', 'total_area_assessed_score',
       'participant', 'correct_answer_percentage_per_class', 'average_score',
       'school_percentile', 'sydney_percentile', 'strength_status',
       'high_distinct_count', 'distinct_count', 'credit_count',
       'participant_count', 'award'],
      dtype='object')
           year      StudentID     Year Level  Question Number  \
count  800000.0  800000.000000  800000.000000    800000.000000
mean     2022.0    8000.500000       6.452562        13.000000
std         0.0    4618.805031       3.463887         7.211107
min      2022.0       1.000000       1.000000         1.000000
25%      2022.0    4000.750000       3.000000         7.000000
50%      2022.0    8000.500000       6.000000        13.000000
75%      2022.0   12000.250000       9.000000        19.000000
max      2022.0   16000.000000      12.000000        25.000000

       sydney_correct_count_percentage  sydney_average_score  \
count                    800000.000000         800000.000000
mean                         49.996598             49.952699
std                          28.866492             28.871227
min                           0.000000              0.000000
25%                          25.030000             24.960000
50%                          49.970000             49.960000
75%                          74.990000             74.890000
max                         100.000000            100.000000

       sydney_participants  student_score  student_total_assessed  \
count         800000.00000  800000.000000           800000.000000
mean              55.02782      49.995712               55.001375
std               26.28256      28.875230               26.256860
min               10.00000       0.000000               10.000000